src/index.js
test/index.js

the code used the filename specified on the db creation.  These
changes use the filename if provided otherwise the originally
configured db.json file name.  These updates apply to both sync and
async saves, but only sync were tested since the API doesn't include a
callback mechanism for the async file write (yet).

save() method wasn't using optionally specified file.  When specified

---

src/disk.js
src/index.js
test/index.js

This is a suggested fix for typicode/lowdb#36.
Opening an empty file or a file that contains only whitespace will act exactly the same as opening a non existing file (before this change you would have gotten an exception).

Fix handling of empty files

---

package.json
src/disk.js

The read function that is exported from disk.js, uses the `fs.readFileSync` function which internally uses fs.readSync. The `fs.readSync` function can fail from time to time and return the following error:
`EAGAIN, resource temporarily unavailable`
graceful-fs patches fs.readSync so it will retry on the EAGAIN error, thus increasing the reliability of `disk.read`.

Replace fs with graceful-fs in disk.js

---

src/index.js

disk.readSync returns a Buffer. JSON.parse (used through low.parse) expects a string, so if given something that is not a string, such as a Buffer, it implicitly converts it to string using toString.
In the former code, we would have 2 conversions from Buffer to string. The first conversion is due the data.trim in the condition (line 93) and the second conversion is when calling JSON.parse (through low.parse in line 95).
In this commit we change it to a single conversion (we trim the Buffer which implicitly converts it to a string and assign the output directly into the data variable, so there's no need for a second conversion on JSON.parse).
This is a small change that can make loading big db files a bit more efficient.
The code remains readable and it's arguably clearer what the data …

Refactor initial data load

---

package.json
src/index.js

Added the `json-parse-helpfulerror` module (the same one that npm uses), that provides helpful errors when failing to parse JSONs.
It's important to note that the actual parsing is still done by the fast native JSON.parse. Only if it failed and throw and error, the module analysis what caused it and outputs a more meaningful error that shows you the token where it failed, including line and column numbers.
It some what relates to the discussion on #36.

Show helpful errors when JSON parsing fails

---

.gitignore
.npmignore
package.json
src/disk.js
src/index.js

Hello typicode:
It has been a while since I use lowdb as my main json db. It is pretty great and works smoothly with all my projects. The only improvement I would like you to take a look at is the support for JavaScript's promise feature.
**In a word, promise support is added to lowdb.**
```javascript
options = _.assign({
autosave: true,
async: true,
promise: false
}, options)
```
1. add function `writePromise()` in disk.js. 
2. add function `db.savePromise()` in index.js. 
3. modify function `_.prototype.value()`  and `save()` in index.js.
All of the modifications above are intended to implement the promise feature. As long as the promise option is set to true, the value() will return a promise:
```javascript
if(options.promise){
return save().then(
function () {
return res
},
function …
```

add the Promise option to lowdb

---

src/index.js

Fixes issue with db.object assigning to itself while using observable objects.
When using a lowdb *source* created from observable libraries such as [mobservable](https://github.com/mweststrate/mobservable) and accessing *lowdb* from inside an observer object, all hell breaks lose.
The test case is pretty difficult to write since it requires a bunch of libraries but the fix is simple.
Could this be included quickly and next version pushed ? I need it :)
Thanks!

Fix issue with an observable db.object assigning to itself

---

examples/README.md

Changed "defauls" to "defaults"

Fix minor typos in examples/README.md

---

README.md
src/_index.js
src/index.node.js

There are 3 things happening here
1. Remove `const { format } = options`, and make format option work
2. Don't overwrite the storage if I only want to change the formatting
3. Fix the readme
Fixes https://github.com/typicode/lowdb/issues/116

Make format option work

---

examples/README.md

Don't use db before its initialised. Add express body parser. Use strings as IDs to allow lookup to work correctly.

Make server example actually work

---

README.md

Fix typo in _.protoype.value() -> _.prototype.value() in readme

Fix typo in _.protoype.value() -> _.prototype.value()

---

README.md

Hi there,
I fixed some issues with the provided examples:
1. `Error: An adapter must be provided, see https://github.com/typicode/lowdb/#usage`
2. We should use two variables here, you can't redeclare a const variable (not copy and paste friendly)
3. Added storing of the collection to the example, as it shows an slightly advanced use case
4. It took me some time to understand, we **need** default values.
About the 3rd: The whole default thing should be placed **way** more prominent in the `README.md`.
It took me some time to figure. Without defaults, the lowdb seems pretty useless (as it doesn't work for me at all).
This might be some mistake on my side, so you might ignore my opinion here. :)
Regards!

Fixed broken lodash-id examples in README.md

---

examples/fp.md

* Add missing `adapter`.
* Calling `low()` with no adapter fails with the following traces as there is no default adapter inside https://github.com/typicode/lowdb/blob/b7eff57a99ef8662ad86e5895ded4b96dfe2137a/src/fp.js#L6 nor https://github.com/typicode/lowdb/blob/b7eff57a99ef8662ad86e5895ded4b96dfe2137a/src/common.js#L3
```sh
/Users/alvaropinot/work/alvaropinot/XXX/node_modules/lowdb/lib/common.js:7
var r = adapter.read();
^
TypeError: Cannot read property 'read' of undefined
at Function.db.read (/Users/alvaropinot/work/alvaropinot/XXX/node_modules/lowdb/lib/common.js:7:21)
at Object.init (/Users/alvaropinot/work/alvaropinot/XXX/node_modules/lowdb/lib/common.js:36:13)
at module.exports (/Users/alvaropinot/work/alvaropinot/XXX/node_modules/lowdb/lib/fp.js:24:17)
at Object.<anonymous> …
```

chore(examples): Fix fp example add adapter

---

README.md
src/Low.ts
src/LowSync.ts

By adding a generic type parameter when initialising the database, we get full type safety when querying. The default is still any so this is not a breaking change. :slightly_smiling_face: 
This allows for something like this:
```ts
interface Post {
id: string;
[key: string]: string;
}
interface PostsDB {
posts: Post[];
}
const adapter = new JSONFile("db.json");
const db = new Low<PostsDB>(adapter);
```

Allow database type to be specified

---

README.md

Based on https://nodejs.org/api/esm.html#esm_no_filename_or_dirname , there is no __dirname available in ES modules in node.js. I edited the usage guide in the README.md file. Also Logical OR assignment (||=) is not supported in node.js v15.x lower, I added a comment to help with that too.

Fixed issue with the usage guide in README.md file

---

src/adapters/LocalStorage.ts

```
error TS2552: Cannot find name 'localStorage'. Did you mean 'LocalStorage'?
```

fix: name 'localStorage' not found

---

src/adapters/TextFile.test.ts

```
error TS2345: Argument of type 'Promise<void>' is not assignable to parameter of type 'never'
```

fix: assign type 'Promise<void>' to type 'never'

---

src/Low.test.ts
src/LowSync.test.ts
src/adapters/JSONFile.test.ts
src/adapters/JSONFileSync.test.ts
src/adapters/LocalStorage.test.ts
src/adapters/Memory.test.ts
src/adapters/MemorySync.test.ts
src/adapters/TextFile.test.ts
src/adapters/TextFileSync.test.ts

There are two types of errors that should not be treated as errors, configure
eslint in the comments to ignore them.
1. @typescript-eslint/require-await, the code does not use await in async, but
we do want a Promise.
2. @typescript-eslint/explicit-module-boundary-types, there is no explicit
return statement in the function, but we really don't care about its return
value.
In order for eslint to make sense, I didn't disable these rules in the file
but to line.

fix: pass eslint

---

package.json

The problem itself is that in `node` module resolution, typescript can't import the subpaths' modules or the modules' types. The problem was not the modules but the types, as this works perfectly in Javascript without types. Investigating I found that there's no way to export many type files to include every type file for every subpath. I tried this at first:
```json
"exports": {
".": {
"import": "./lib/index.js",
"types": "./lib/index.d.ts"
},
"./node": {
"import": "./lib/node.js",
"types": "./lib/node.d.ts"
},
"./browser": {
"import": "./lib/browser.js",
"types": "./lib/browser.d.ts"
}
```
But the types weren't being exported. I tried to find the solution in the typescript documentation, but there's no article regarding subpaths, so I think there's no native support for subpath types. …

fix: imported subpaths types correctly

---

README.md

In examples, fixed imports and added missing arguments in `Low` calls.

Docs: Fixed outdated examples
